# Generated by Django 4.0.3 on 2023-01-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=12, unique=True, verbose_name='nickname'),
        ),
    ]
