# Generated by Django 4.0.6 on 2023-05-08 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_alert', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alert', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
