# Generated by Django 4.0.6 on 2023-09-01 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_lectureslink'),
        ('common', '0002_data_notification_delete_alert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='NotificationDetail',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='data',
            new_name='detail',
        ),
    ]
