# Generated by Django 4.0.6 on 2023-05-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
