# Generated by Django 4.0.6 on 2022-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='free_board'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
