# Generated by Django 4.0.6 on 2023-08-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_delete_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('category', models.SmallIntegerField()),
                ('teacher', models.SmallIntegerField()),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
